default_stages: [ commit ]

repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [ commit ]

  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
        stages: [ commit ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        stages: [ commit ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: mixed-line-ending
        stages: [ commit ]

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0  # or master if you're bold
    hooks:
      - id: interrogate
        args: [.]
